const initCtX = {
  colors: {
    brand1: '#0067a5',
    brand2: '#0033B9',
    brand3: '#dedede',
    brand4: '#535353',
    brand5: '#225271',
    brand6: '#005e96',
    brand7: '#666',
    brand8: '#999',
    brand9: '#C6C6C6',
    brand10: '#A3A3A3',
    msgLogin: 'black',
  },
  textSizes: {
    xlarge: 20,
    large: 18,
    medium: 16,
    normal: 14,
    small: 12,
    xsmall: 10,
  },
  apiData: {
    A1: {},
    A2: {
      selectedID: '',
      mockData: {
        fff1: {
          id: 'fff1',
          userName: 'Juliana da Silva',
          entity: 'Governo do Estado da AZ Tecnologia',
          imgUrl: 'https://nerdin.com.br/img/empresa/1122.jpg',
        },
        fff2: {
          id: 'fff2',
          userName: 'Rodrigo',
          entity: 'Outro Órgão',
          imgUrl: 'https://nerdin.com.br/img/empresa/1122.jpg',
        },
      },
      selectedData: {
        id: 'fff1',
        userName: 'Juliana da Silva',
        entity: 'Governo do Estado da AZ Tecnologia',
        imgUrl: 'https://nerdin.com.br/img/empresa/1122.jpg',
        totalPatrimonios: '0',
        totalSetores: '0',
      },
    },
    A3: { selectedID: '', mockData: {}, selectedData: {} },
    A4: {
      selectedID: '',
      mockData: {
        1: {
          id: '1',
          navBarTitle: 'Inventário 001/2022',
          status: 'Em andamento',
          period: '01/02/2022 a 10/10/2022',
          observation:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc cursus nisl sed dolor pellentesque, ut eleifend lectus elementum.',
          fileName: 'portaria1240-2022.pdf',
          fileUrl: 'http://firebase.web.app/file1240',
          agencies: {
            allData: [
              { id: '129', name: 'AGEHAB', status: 'Em Andamento' },
              { id: '8773', name: 'AGEPAN', status: 'Não Iniciado' },
            ],
            filtered: [
              { id: '129', name: 'AGEHAB', status: 'Em Andamento' },
              { id: '8773', name: 'AGEPAN', status: 'Não Iniciado' },
            ],
          },
        },
        2: {
          id: '2',
          navBarTitle: 'Inventário 002/2022',
          name: 'Inventário 002/2022',
          status: 'Finalizado',
          period: '01/02/2022 a 10/10/2022',
          observation:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit..',
          fileName: 'file547_3A.pdf',
          fileUrl: 'http://firebase.web.app/file1240',
          agencies: {
            allData: [
              { id: 'ttt1', name: 'Correios', status: 'Finalizado' },
              {
                id: 'ttt2',
                name: 'Prefeitura de Osasco',
                status: 'Não Iniciado',
              },
              { id: 'ttt3', name: 'Outro Orgão 1', status: 'Em Andamento' },
              { id: 'ttt4', name: 'Outro Órgão 2', status: 'Não Iniciado' },
            ],
            filtered: [
              { id: 'ttt1', name: 'Correios', status: 'Finalizado' },
              {
                id: 'ttt2',
                name: 'Prefeitura de Osasco',
                status: 'Não Iniciado',
              },
              { id: 'ttt3', name: 'Outro Orgão 1', status: 'Em Andamento' },
              { id: 'ttt4', name: 'Outro Órgão 2', status: 'Não Iniciado' },
            ],
          },
        },
      },
      selectedData: {},
    },
    A5: {
      comissions: [],
      selectedID: '',
      mockData: {},
      selectedData: {
        id: '129',
        navbarTitle: 'Inventário 2022',
        agency: 'AGEHAB',
        status: 'Em andamento',
        detailsTitle: 'Comissão 001',
        details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        sectors: {
          allData: [
            { id: '1', name: 'Marketing', status: 'Finalizado', count: '20' },
            {
              id: 'zzz1B',
              name: 'Jurídico',
              status: 'Finalizado',
              count: '118',
            },
            {
              id: 'zzz1C',
              name: 'Financeiro',
              status: 'Finalizado',
              count: '37',
            },
          ],
          filtered: [
            { id: '1', name: 'Marketing', status: 'Finalizado', count: '20' },
            {
              id: 'zzz1B',
              name: 'Jurídico',
              status: 'Finalizado',
              count: '118',
            },
            {
              id: 'zzz1C',
              name: 'Financeiro',
              status: 'Finalizado',
              count: '37',
            },
          ],
        },
      },
    },
    A6: {
      comissions: [],
      mockData: {
        zzz1A: {
          id: 'zzz1A',
          navbarTitle: 'Inventário 2022',
          agency: 'AGEHAB',
          sector: 'Marketing',
          count: '26',
          tabBarCount1: '2',
          tabBarCount2: '3',
          inventories: [
            {
              id: 'zzz1A1',
              desc: 'Cadeira Giratória Presidente',
              conservation: 'Ótimo',
              icon: 'check',
              image:
                'https://a-static.mlcdn.com.br/800x560/cadeira-de-escritorio-presidente-pneumatica-giratoria-preta-duoffice/duoffice/656636890/b0b2965f40259cdff9811bf1838fde0d.jpeg',
            },
            {
              id: 'zzz1A2',
              desc: 'Gaveteiro Maia 3 GV Castanho',
              conservation: 'Ótimo',
              icon: 'check',
              image:
                'https://staticmobly.akamaized.net/p/Politorno-Gaveteiro-Maia-3-GV-Castanho-7296-010306-1-zoom.jpg',
            },
          ],
          pendings: [
            {
              id: 'zzz1A3',
              code: '021547895',
              desc: 'Calculadora Científica 552 funções...',
            },
            {
              id: 'zzz1A4',
              code: '021547895',
              desc: 'Cadeira giratória modelo 5326m',
            },
            { id: 'zzz1A5', code: '021547895', desc: 'Mesa vidro modelo A425' },
          ],
        },
        zzz1B: {
          id: 'zzz1B',
          navbarTitle: 'Inventário 2022',
          agency: 'AGEHAB',
          sector: 'Jurídico',
          status: 'Finalizado',
          count: '118',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        zzz1C: {
          id: 'zzz1C',
          navbarTitle: 'Inventário 2022',
          agency: 'AGEHAB',
          sector: 'Financeiro',
          status: 'Finalizado',
          count: '37',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        zzzB1: {
          id: 'zzzB1',
          navbarTitle: 'Inventário 2022',
          agency: 'AGEPAN',
          sector: 'Administração',
          status: 'Não Iniciado',
          count: '17',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        zzzB2: {
          id: 'zzzB2',
          navbarTitle: 'Inventário 2022',
          agency: 'AGEPAN',
          sector: 'Copa',
          status: 'Finalizado 2',
          count: '280',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        zzzB3: {
          id: 'zzzB3',
          navbarTitle: 'Inventário 2022',
          agency: 'AGEPAN',
          sector: 'Projetos',
          status: 'Em Andamento',
          count: '05',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        zzzC1: {
          id: 'zzzC1',
          navbarTitle: 'Inventário 2022',
          agency: 'AGRAER',
          sector: 'Logística',
          status: 'Não Iniciado',
          count: '733',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        zzzC2: {
          id: 'zzzC2',
          navbarTitle: 'Inventário 2022',
          agency: 'AGRAER',
          sector: 'TI - Tecnologia da Informação',
          status: 'Finalizado',
          count: '1000+',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        zzzC3: {
          id: 'zzzC3',
          navbarTitle: 'Inventário 2022',
          agency: 'AGRAER',
          sector: 'Operacional',
          status: 'Finalizado',
          count: '60',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        zzzC4: {
          id: 'zzzC4',
          navbarTitle: 'Inventário 2022',
          agency: 'AGRAER',
          sector: 'Comercial',
          status: 'Finalizado',
          count: '247',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        zzzC5: {
          id: 'zzzC5',
          navbarTitle: 'Inventário 2022',
          agency: 'AGRAER',
          sector: 'Planejamento',
          status: 'Não Iniciado',
          count: '48',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        zzzC6: {
          id: 'zzzC6',
          navbarTitle: 'Inventário 2022',
          agency: 'AGRAER',
          sector: 'Produção',
          status: 'Finalizado',
          count: '155',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        zzzD1: {
          id: 'zzzD1',
          navbarTitle: 'Inventário 2022',
          agency: 'DETRAN',
          sector: 'Administração',
          status: 'Não Iniciado',
          count: '12',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        zzzD2: {
          id: 'zzzD2',
          navbarTitle: 'Inventário 2022',
          agency: 'DETRAN',
          sector: 'Copa',
          status: 'Finalizado',
          count: '1000+',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        zzzD3: {
          id: 'zzzD3',
          navbarTitle: 'Inventário 2022',
          agency: 'DETRAN',
          sector: 'Financeiro',
          status: 'Finalizado',
          count: '50',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        tttA1: {
          id: 'tttA1',
          navbarTitle: 'Inventário 2022',
          agency: 'Correios',
          sector: 'Administrativo',
          status: 'Finalizado',
          count: '40',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        tttA2: {
          id: 'tttA2',
          navbarTitle: 'Inventário 2022',
          agency: 'Correios',
          sector: 'Operacões',
          status: 'Finalizado',
          count: '180',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        tttA3: {
          id: 'tttA3',
          navbarTitle: 'Inventário 2022',
          agency: 'Correios',
          sector: 'Logística',
          status: 'Finalizado',
          count: '180',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        tttB1: {
          id: 'tttB1',
          navbarTitle: 'Inventário 2022',
          agency: 'Pref. Osasco',
          sector: 'Administração',
          status: 'Não Iniciado',
          count: '17',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        tttB2: {
          id: 'tttB2',
          navbarTitle: 'Inventário 2022',
          agency: 'Pref. Osasco',
          sector: 'Copa',
          status: 'Em Andamento',
          count: '280',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        tttB3: {
          id: 'tttB3',
          navbarTitle: 'Inventário 2022',
          agency: 'Pref. Osasco',
          sector: 'Tesouraria',
          status: 'Finalizado',
          count: '47',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        tttC1: {
          id: 'tttC1',
          navbarTitle: 'Inventário 2022',
          agency: 'Sectors of Org. 1',
          sector: 'Administração',
          status: 'Não Iniciado',
          count: '06',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        tttC2: {
          id: 'tttC2',
          navbarTitle: 'Inventário 2022',
          agency: 'Sectors of Org. 1',
          sector: 'Manutenção',
          status: 'Finalizado',
          count: '15',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        tttC3: {
          id: 'tttC3',
          navbarTitle: 'Inventário 2022',
          agency: 'Sectors of Org. 1Pref. Osasco',
          sector: 'Projetos',
          status: 'Finalizado',
          count: '22',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        tttD1: {
          id: 'tttD1',
          navbarTitle: 'Inventário 2022',
          agency: 'Sectors of Org. 2',
          sector: 'Administração',
          status: 'Não Iniciado',
          count: '12',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        tttD2: {
          id: 'tttD2',
          navbarTitle: 'Inventário 2022',
          agency: 'Sectors of Org. 2',
          sector: 'Copa',
          status: 'Finalizado',
          count: '1000+',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
        tttD3: {
          id: 'tttD3',
          navbarTitle: 'Inventário 2022',
          agency: 'Sectors of Org. 2',
          sector: 'Financeiro',
          status: 'Finalizado',
          count: '50',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: [],
          inventories: [],
        },
      },
      selectedData: {},
    },
    A8: {
      selectedID: '',
      mockData: {
        zzz1A1: {
          id: 'zzz1A1',
          navbarTitle: 'Inventário 2022',
          agency: 'AGEHAB',
          sector: 'Marketing',
          code: '0189632553',
          codeBar: '',
          desc: 'Cadeira Giratória Presidente',
          obs: 'Lorem ipsum dolor sit...',
          conservation: 'Ótimo',
          icon: 'check',
          image:
            'https://a-static.mlcdn.com.br/800x560/cadeira-de-escritorio-presidente-pneumatica-giratoria-preta-duoffice/duoffice/656636890/b0b2965f40259cdff9811bf1838fde0d.jpeg',
          images: [
            'https://a-static.mlcdn.com.br/280x210/cadeira-presidente-elegant-giratoria-preto-mymax-maxoffice/mymax/25009123/ac6327b78f6d5d3fc939d5d74f864b3e.jpeg',
            'https://blog.nscsports.org/wp-content/uploads/2014/10/default-img.gif',
            'https://http2.mlstatic.com/D_NQ_NP_717251-MLB51740844343_092022-O.webp',
          ],
          status: 'Finalizado',
          count: '20',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          pickerList: [
            { value: '1', label: 'Ótimo' },
            { value: '2', label: 'Bom' },
            { value: '3', label: 'Ruim' },
          ],
        },
        zzz1A2: {
          id: 'zzz1A2',
          navbarTitle: 'Inventário 2022',
          agency: 'AGEHAB',
          sector: 'Marketing',
          code: '24359888632',
          codeBar: '',
          desc: 'Gaveteiro Maia 3 GV Castanho',
          obs: 'Lorem ipsum dolor sit...',
          conservation: 'Ótimo',
          icon: 'check',
          image:
            'https://staticmobly.akamaized.net/p/Politorno-Gaveteiro-Maia-3-GV-Castanho-7296-010306-1-zoom.jpg',
          images: [
            'https://staticmobly.akamaized.net/r/2000x2000/p/Politorno-Gaveteiro-Maia-3-GV-Castanho-7302-010306-5.jpg',
            'https://staticmobly.akamaized.net/r/2000x2000/p/Politorno-Gaveteiro-Maia-3-GV-Castanho-7301-010306-4.jpg',
            'https://staticmobly.akamaized.net/p/Politorno-Gaveteiro-Maia-3-GV-Castanho-7296-010306-1-zoom.jpg',
          ],
          status: 'Finalizado',
          count: '20',
          details:
            'Estrutura em MDP 15 mm; Frente e Lateral da Gaveta em MDP 15 mm;',
          pickerList: [
            { value: '1', label: 'Ótimo' },
            { value: '2', label: 'Bom' },
            { value: '3', label: 'Ruim' },
          ],
        },
      },
      selectedData: {
        id: 'zzz1A1',
        navbarTitle: 'Inventário 2022',
        agency: 'AGEHAB',
        sector: 'Marketing',
        code: '0189632553',
        codeBar: '',
        desc: 'Teste do Qr Code',
        obs: 'Lorem ipsum dolor sit...',
        conservation: 'Ótimo',
        icon: 'check',
        image:
          'https://a-static.mlcdn.com.br/800x560/cadeira-de-escritorio-presidente-pneumatica-giratoria-preta-duoffice/duoffice/656636890/b0b2965f40259cdff9811bf1838fde0d.jpeg',
        images: [
          'https://a-static.mlcdn.com.br/280x210/cadeira-presidente-elegant-giratoria-preto-mymax-maxoffice/mymax/25009123/ac6327b78f6d5d3fc939d5d74f864b3e.jpeg',
          'https://blog.nscsports.org/wp-content/uploads/2014/10/default-img.gif',
          'https://http2.mlstatic.com/D_NQ_NP_717251-MLB51740844343_092022-O.webp',
        ],
        status: 'Finalizado',
        count: '20',
        details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        pickerList: [
          { value: '1', label: 'Ótimo' },
          { value: '2', label: 'Bom' },
          { value: '3', label: 'Ruim' },
        ],
      },
    },
  },
  toggles: {
    apiError: false,
    loadMore: true,
    loading: false,
    sideMenu: false,
    observationModal: false,
    conservStateModal: false,
    codeReader: { qrCode: false, barCode: true, writeCode: false },
    A3: { loadMore: false },
    A4: { details: false, loadMore: false },
    A5: { details: false, loadMore: false },
    A6: {
      inv: { initialList: true, loadMore: false },
      pend: { loadMore: false },
      btnFinish: false,
      modalTypeWrite: false,
      details: false,
      inventaries: true,
      pending: false,
    },
    A7: {
      validation: {
        showSuccess: false,
        msgSuccess: 'Patrimonio Inventariado com sucesso!',
        msgError: 'Erro!',
        showError: false,
      },
    },
    A8: {
      diffLocality: true,
      sectorInv: false,
      btnWrite: false,
      gallery: false,
      btnNotFound: true,
    },
  },
  '----- NEW VARIABLES -----': '----- NEW VARIABLES -----',
  colors2: {
    brand1: '#0067a5',
    brand2: '#0033B9',
    brand3: '#dedede',
    brand4: '#ddd',
    brand5: '#025384',
    brand6: '#005e96',
    brand7: '#666',
    brand8: '#999',
  },
  textSizes2: {
    xlarge: '20',
    large: '18',
    medium: '16',
    normal: '14',
    small: '12',
    xsmall: '10',
  },
  toggles2: {
    apiError: false,
    loadMore: true,
    loading: false,
    sideMenu: false,
    observationModal: false,
    conservStateModal: false,
    codeReader: {
      qrCode: false,
      barCode: true,
      writeCode: false,
      addNew: 'true',
    },
    A3: {
      loadMore: false,
    },
    A4: {
      details: false,
      loadMore: false,
    },
    A5: {
      details: false,
      loadMore: false,
    },
    A6: {
      btnFinish: false,
      modalTypeWrite: false,
      details: false,
      inventaries: true,
      pending: false,
    },
    A7: {
      validation: {
        showSuccess: false,
        msgSuccess: 'Patrimonio Inventariado com sucesso',
        msgError: 'Erro!',
        showError: false,
      },
    },
    A8: {
      sectorInv: false,
      btnWrite: false,
      gallery: false,
      btnNotFound: true,
      newRequest: 'false',
    },
    A9: {
      includes: 'includes',
    },
  },
  apiData2: {
    A1: {
      'propriedade sem nome': '',
    },
    A2: {
      selectedID: '',
      mockData: {
        fff1: {
          id: 'fff1',
          userName: 'Juliana da Silva',
          entity: 'Governo do Estado da AZ Tecnologia',
          imgUrl: 'https://nerdin.com.br/img/empresa/1122.jpg',
        },
        fff2: {
          id: 'fff2',
          userName: 'Rodrigo',
          entity: 'Outro Órgão',
          imgUrl: 'https://nerdin.com.br/img/empresa/1122.jpg',
        },
      },
      selectedData: {
        id: 'fff1',
        userName: 'Juliana da Silva',
        entity: 'Governo do Estado da AZ Tecnologia',
        imgUrl: 'https://nerdin.com.br/img/empresa/1122.jpg',
        totalPatrimonios: '0',
        totalSetores: '0',
      },
    },
    A3: {
      selectedID: '',
      mockData: {
        'propriedade sem nome': '',
      },
      selectedData: {
        'propriedade sem nome': '',
      },
    },
    A4: {
      selectedID: '',
      mockData: {
        '1': {
          id: '1',
          navBarTitle: 'Inventário 001/2022',
          status: 'Em andamento',
          period: '01/02/2022 a 10/10/2022',
          observation:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc cursus nisl sed dolor pellentesque, ut eleifend lectus elementum.',
          fileName: 'portaria1240-2022.pdf',
          fileUrl: 'http://firebase.web.app/file1240',
          agencies: {
            allData: [
              {
                id: '129',
                name: 'AGEHAB',
                status: 'Em Andamento',
              },
              {
                id: '8773',
                name: 'AGEPAN',
                status: 'Não Iniciado',
              },
            ],
            filtered: [
              {
                id: '129',
                name: 'AGEHAB',
                status: 'Em Andamento',
              },
              {
                id: '8773',
                name: 'AGEPAN',
                status: 'Não Iniciado',
              },
            ],
          },
        },
        '2': {
          id: '2',
          navBarTitle: 'Inventário 002/2022',
          name: 'Inventário 002/2022',
          status: 'Finalizado',
          period: '01/02/2022 a 10/10/2022',
          observation:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit..',
          fileName: 'file547_3A.pdf',
          fileUrl: 'http://firebase.web.app/file1240',
          agencies: {
            allData: [
              {
                id: 'ttt1',
                name: 'Correios',
                status: 'Finalizado',
              },
              {
                id: 'ttt2',
                name: 'Prefeitura de Osasco',
                status: 'Não Iniciado',
              },
              {
                id: 'ttt3',
                name: 'Outro Orgão 1',
                status: 'Em Andamento',
              },
              {
                id: 'ttt4',
                name: 'Outro Órgão 2',
                status: 'Não Iniciado',
              },
            ],
            filtered: [
              {
                id: 'ttt1',
                name: 'Correios',
                status: 'Finalizado',
              },
              {
                id: 'ttt2',
                name: 'Prefeitura de Osasco',
                status: 'Não Iniciado',
              },
              {
                id: 'ttt3',
                name: 'Outro Orgão 1',
                status: 'Em Andamento',
              },
              {
                id: 'ttt4',
                name: 'Outro Órgão 2',
                status: 'Não Iniciado',
              },
            ],
          },
        },
      },
      selectedData: {
        'propriedade sem nome': '',
      },
    },
    A5: {
      comissions: ['Sem Valor'],
      selectedID: '',
      mockData: {
        'propriedade sem nome': '',
      },
      selectedData: {
        id: '129',
        navbarTitle: 'Inventário 2022',
        agency: 'AGEHAB',
        status: 'Em andamento',
        detailsTitle: 'Comissão 001',
        details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        sectors: {
          allData: [
            {
              id: '1',
              name: 'Marketing',
              status: 'Finalizado',
              count: '20',
            },
            {
              id: 'zzz1B',
              name: 'Jurídico',
              status: 'Finalizado',
              count: '118',
            },
            {
              id: 'zzz1C',
              name: 'Financeiro',
              status: 'Finalizado',
              count: '37',
            },
          ],
          filtered: [
            {
              id: '1',
              name: 'Marketing',
              status: 'Finalizado',
              count: '20',
            },
            {
              id: 'zzz1B',
              name: 'Jurídico',
              status: 'Finalizado',
              count: '118',
            },
            {
              id: 'zzz1C',
              name: 'Financeiro',
              status: 'Finalizado',
              count: '37',
            },
          ],
        },
      },
    },
    A6: {
      comissions: ['Sem Valor'],
      mockData: {
        zzz1A: {
          id: 'zzz1A',
          navbarTitle: 'Inventário 2022',
          agency: 'AGEHAB',
          sector: 'Marketing',
          count: '26',
          tabBarCount1: '2',
          tabBarCount2: '3',
          inventories: [
            {
              id: 'zzz1A1',
              desc: 'Cadeira Giratória Presidente',
              conservation: 'Ótimo',
              icon: 'check',
              image:
                'https://a-static.mlcdn.com.br/800x560/cadeira-de-escritorio-presidente-pneumatica-giratoria-preta-duoffice/duoffice/656636890/b0b2965f40259cdff9811bf1838fde0d.jpeg',
            },
            {
              id: 'zzz1A2',
              desc: 'Gaveteiro Maia 3 GV Castanho',
              conservation: 'Ótimo',
              icon: 'check',
              image:
                'https://staticmobly.akamaized.net/p/Politorno-Gaveteiro-Maia-3-GV-Castanho-7296-010306-1-zoom.jpg',
            },
          ],
          pendings: [
            {
              id: 'zzz1A3',
              code: '021547895',
              desc: 'Calculadora Científica 552 funções...',
            },
            {
              id: 'zzz1A4',
              code: '021547895',
              desc: 'Cadeira giratória modelo 5326m',
            },
            {
              id: 'zzz1A5',
              code: '021547895',
              desc: 'Mesa vidro modelo A425',
            },
          ],
        },
        zzz1B: {
          id: 'zzz1B',
          navbarTitle: 'Inventário 2022',
          agency: 'AGEHAB',
          sector: 'Jurídico',
          status: 'Finalizado',
          count: '118',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        zzz1C: {
          id: 'zzz1C',
          navbarTitle: 'Inventário 2022',
          agency: 'AGEHAB',
          sector: 'Financeiro',
          status: 'Finalizado',
          count: '37',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        zzzB1: {
          id: 'zzzB1',
          navbarTitle: 'Inventário 2022',
          agency: 'AGEPAN',
          sector: 'Administração',
          status: 'Não Iniciado',
          count: '17',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        zzzB2: {
          id: 'zzzB2',
          navbarTitle: 'Inventário 2022',
          agency: 'AGEHAB',
          sector: 'Copa',
          status: 'Finalizado 2',
          count: '280',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        zzzB3: {
          id: 'zzzB3',
          navbarTitle: 'Inventário 2022',
          agency: 'AGEHAB',
          sector: 'Projetos',
          status: 'Em Andamento',
          count: '05',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        zzzC1: {
          id: 'zzzC1',
          navbarTitle: 'Inventário 2022',
          agency: 'AGRAER',
          sector: 'Logística',
          status: 'Não Iniciado',
          count: '733',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        zzzC2: {
          id: 'zzzC2',
          navbarTitle: 'Inventário 2022',
          agency: 'AGRAER',
          sector: 'TI - Tecnologia da Informação',
          status: 'Finalizado',
          count: '1000+',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        zzzC3: {
          id: 'zzzC3',
          navbarTitle: 'Inventário 2022',
          agency: 'AGRAER',
          sector: 'Operacional',
          status: 'Finalizado',
          count: '60',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        zzzC4: {
          id: 'zzzC4',
          navbarTitle: 'Inventário 2022',
          agency: 'AGRAER',
          sector: 'Comercial',
          status: 'Finalizado',
          count: '247',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        zzzC5: {
          id: 'zzzC5',
          navbarTitle: 'Inventário 2022',
          agency: 'AGRAER',
          sector: 'Planejamento',
          status: 'Não Iniciado',
          count: '48',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        zzzC6: {
          id: 'zzzC6',
          navbarTitle: 'Inventário 2022',
          agency: 'AGRAER',
          sector: 'Produção',
          status: 'Finalizado',
          count: '155',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        zzzD1: {
          id: 'zzzD1',
          navbarTitle: 'Inventário 2022',
          agency: 'DETRAN',
          sector: 'Administração',
          status: 'Não Iniciado',
          count: '12',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        zzzD2: {
          id: 'zzzD2',
          navbarTitle: 'Inventário 2022',
          agency: 'DETRAN',
          sector: 'Copa',
          status: 'Finalizado',
          count: '1000+',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        zzzD3: {
          id: 'zzzD3',
          navbarTitle: 'Inventário 2022',
          agency: 'DETRAN',
          sector: 'Financeiro',
          status: 'Finalizado',
          count: '50',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        tttA1: {
          id: 'tttA1',
          navbarTitle: 'Inventário 2022',
          agency: 'Correios',
          sector: 'Administrativo',
          status: 'Finalizado',
          count: '40',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        tttA2: {
          id: 'tttA2',
          navbarTitle: 'Inventário 2022',
          agency: 'Correios',
          sector: 'Operacões',
          status: 'Finalizado',
          count: '180',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        tttA3: {
          id: 'tttA3',
          navbarTitle: 'Inventário 2022',
          agency: 'Correios',
          sector: 'Logística',
          status: 'Finalizado',
          count: '180',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        tttB1: {
          id: 'tttB1',
          navbarTitle: 'Inventário 2022',
          agency: 'Pref. Osasco',
          sector: 'Administração',
          status: 'Não Iniciado',
          count: '17',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        tttB2: {
          id: 'tttB2',
          navbarTitle: 'Inventário 2022',
          agency: 'Pref. Osasco',
          sector: 'Copa',
          status: 'Em Andamento',
          count: '280',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        tttB3: {
          id: 'tttB3',
          navbarTitle: 'Inventário 2022',
          agency: 'Pref. Osasco',
          sector: 'Tesouraria',
          status: 'Finalizado',
          count: '47',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        tttC1: {
          id: 'tttC1',
          navbarTitle: 'Inventário 2022',
          agency: 'Sectors of Org. 1',
          sector: 'Administração',
          status: 'Não Iniciado',
          count: '06',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        tttC2: {
          id: 'tttC2',
          navbarTitle: 'Inventário 2022',
          agency: 'Sectors of Org. 1',
          sector: 'Manutenção',
          status: 'Finalizado',
          count: '15',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        tttC3: {
          id: 'tttC3',
          navbarTitle: 'Inventário 2022',
          agency: 'Sectors of Org. 1',
          sector: 'Projetos',
          status: 'Finalizado',
          count: '22',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        tttD1: {
          id: 'tttD1',
          navbarTitle: 'Inventário 2022',
          agency: 'Sectors of Org. 2',
          sector: 'Administração',
          status: 'Não Iniciado',
          count: '12',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        tttD2: {
          id: 'tttD2',
          navbarTitle: 'Inventário 2022',
          agency: 'Sectors of Org. 2',
          sector: 'Copa',
          status: 'Finalizado',
          count: '1000+',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
        tttD3: {
          id: 'tttD3',
          navbarTitle: 'Inventário 2022',
          agency: 'Sectors of Org. 2',
          sector: 'Financeiro',
          status: 'Finalizado',
          count: '50',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          tabBarTitle1: 'Inventariados',
          tabBarCount1: '3',
          tabBarTitle2: 'Pendentes',
          tabBarCount2: '3',
          msg1: 'Utilize a câmera para scanear os patrimônios',
          pendings: ['Sem Valor'],
          inventories: ['Sem Valor'],
        },
      },
      selectedData: {
        'propriedade sem nome': '',
      },
    },
    A7: {
      modalNotFound: '',
    },
    A8: {
      selectedID: '',
      mockData: {
        zzz1A1: {
          id: 'zzz1A1',
          navbarTitle: 'Inventário 2022',
          agency: 'AGEHAB',
          sector: 'Marketing',
          code: '0189632553',
          codeBar: '',
          desc: 'Cadeira Giratória Presidente',
          obs: 'Lorem ipsum dolor sit...',
          conservation: 'Ótimo',
          icon: 'check',
          image:
            'https://a-static.mlcdn.com.br/800x560/cadeira-de-escritorio-presidente-pneumatica-giratoria-preta-duoffice/duoffice/656636890/b0b2965f40259cdff9811bf1838fde0d.jpeg',
          images: [
            'https://a-static.mlcdn.com.br/280x210/cadeira-presidente-elegant-giratoria-preto-mymax-maxoffice/mymax/25009123/ac6327b78f6d5d3fc939d5d74f864b3e.jpeg',
            'https://blog.nscsports.org/wp-content/uploads/2014/10/default-img.gif',
            'https://http2.mlstatic.com/D_NQ_NP_717251-MLB51740844343_092022-O.webp',
          ],
          status: 'Finalizado',
          count: '20',
          details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          pickerList: [
            {
              value: '1',
              label: 'Ótimo',
            },
            {
              value: '2',
              label: 'Bom',
            },
            {
              value: '3',
              label: 'Ruim',
            },
          ],
        },
        zzz1A2: {
          id: 'zzz1A2',
          navbarTitle: 'Inventário 2022',
          agency: 'AGEHAB',
          sector: 'Marketing',
          code: '24359888632',
          codeBar: '',
          desc: 'Gaveteiro Maia 3 GV Castanho',
          obs: 'Lorem ipsum dolor sit...',
          conservation: 'Ótimo',
          icon: 'check',
          image:
            'https://staticmobly.akamaized.net/p/Politorno-Gaveteiro-Maia-3-GV-Castanho-7296-010306-1-zoom.jpg',
          images: [
            'https://staticmobly.akamaized.net/r/2000x2000/p/Politorno-Gaveteiro-Maia-3-GV-Castanho-7302-010306-5.jpg',
            'https://staticmobly.akamaized.net/r/2000x2000/p/Politorno-Gaveteiro-Maia-3-GV-Castanho-7301-010306-4.jpg',
            'https://staticmobly.akamaized.net/p/Politorno-Gaveteiro-Maia-3-GV-Castanho-7296-010306-1-zoom.jpg',
          ],
          status: 'Finalizado',
          count: '20',
          details:
            'Estrutura em MDP 15 mm; Frente e Lateral da Gaveta em MDP 15 mm;',
          pickerList: [
            {
              value: '1',
              label: 'Ótimo',
            },
            {
              value: '2',
              label: 'Bom',
            },
            {
              value: '3',
              label: 'Ruim',
            },
          ],
        },
      },
      selectedData: {
        id: 'zzz1A1',
        navbarTitle: 'Inventário 2022',
        agency: 'AGEHAB',
        sector: 'Marketing',
        code: '0189632553',
        codeBar: '',
        desc: 'Teste do Qr Code',
        obs: 'Lorem ipsum dolor sit...',
        conservation: 'Ótimo',
        icon: 'check',
        image:
          'https://a-static.mlcdn.com.br/800x560/cadeira-de-escritorio-presidente-pneumatica-giratoria-preta-duoffice/duoffice/656636890/b0b2965f40259cdff9811bf1838fde0d.jpeg',
        images: [
          'https://a-static.mlcdn.com.br/280x210/cadeira-presidente-elegant-giratoria-preto-mymax-maxoffice/mymax/25009123/ac6327b78f6d5d3fc939d5d74f864b3e.jpeg',
          'https://blog.nscsports.org/wp-content/uploads/2014/10/default-img.gif',
          'https://http2.mlstatic.com/D_NQ_NP_717251-MLB51740844343_092022-O.webp',
        ],
        status: 'Finalizado',
        count: '20',
        details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        pickerList: [
          {
            value: '1',
            label: 'Ótimo',
          },
          {
            value: '2',
            label: 'Bom',
          },
          {
            value: '3',
            label: 'Ruim',
          },
        ],
      },
    },
    A9: {
      carousel: [
        {
          id: 0,
          name: 'name_0',
        },
      ],
      carousel2: [
        {
          id: '2',
          name: 'test2',
        },
      ],
      selectedData: {
        navbarTitle: 'Incluir Patrimônio',
        navbarTitle2: 'Incluir Patrimônio',
      },
    },
  },
  true: 'true',
  content: {
    A1: {
      navBarTitle: {
        ptBr: 'RECOMENDAÇÕES',
      },
    },
    A2: {
      navBarTitle: {
        ptBr: 'RECOMENDAÇÕES',
      },
      others: 'Unidades',
    },
    A3: {
      navBarTitle: {
        ptBr: 'Inventários',
      },
    },
    A4: {
      navBarTitle: {
        ptBr: 'Inventários',
      },
      period: {
        ptBr: 'Período Inventário',
      },
      observation: {
        ptBr: 'Observações',
      },
      fileName: {
        ptBr: 'Arquivo',
      },
      search: {
        ptBr: 'Busque por órgão',
      },
    },
    A5: {
      search: {
        ptBr: 'Busque por Unidade Organizacional',
      },
    },
    A6: {
      tabBarTitle1: {
        ptBr: 'Inventariados',
      },
      tabBarTitle2: {
        ptBr: 'Pendentes',
      },
      tabBarTitle3: {
        ptBr: 'SOLICITAÇÕES',
      },
      msg1: {
        ptBr: 'Utilize a câmera para scanear os patrimônios',
      },
    },
    A7: {
      navBarTitle: {
        ptBr: 'POSICIONE O CÓDIGO NA MARCAÇÃO',
      },
      writeCode: {
        button: {
          ptBr: 'Buscar Patrimônio',
        },
      },
    },
    A8: {
      titlePending: {
        ptBr: 'Patrimônio Pendente',
      },
      titleInv: {
        ptBr: 'Patrimônio Inventariado!',
      },
      invSector: {
        ptBr: 'Unidade Organizacional Inventariada',
      },
      desc: {
        ptBr: 'Descrição',
      },
      agency: {
        ptBr: 'Órgão Responsável',
      },
      sector: {
        ptBr: 'Unidade Organizacional',
      },
      conservation: {
        ptBr: [
          [
            {
              nome: 'carregando',
              id: 1,
            },
            'Teste',
          ],
        ],
      },
      observation: {
        ptBr: 'Observação',
      },
      regSector: {
        ptBr: 'Unidade Organizacional Cadastrada',
      },
      title: {
        ptBr: 'Patrimônio',
      },
    },
    common: {
      loadMore: {
        ptBr: 'Carregar Mais',
      },
    },
  },
  userData: {
    displayName: '...',
    email: '...',
    photoUrl: '...',
  },
  formsData: {
    A1: {
      iptsChanges: {
        userEmail: '',
        userPassword: '',
      },
    },
    A4: {
      iptsChanges: {
        search: '',
      },
    },
    A5: {
      iptsChanges: {
        search: '',
      },
    },
    A8: {
      iptsChanges: {
        observation: '',
        conservation: {
          nome: '',
          id: '',
        },
        condNewRequest: 'false',
        description: '-',
      },
      condNotFound: 'false',
      condPending: 'true',
      condPicker: 'false',
      condConserv: 'null',
    },
  },
  dev: {
    messages: {
      showLogin: false,
      login: 'Mensagem do Login',
    },
  },
  endpoint: 'https://www.siga.ms.gov.br',
  listsData: {
    A3: {
      currPage: 1,
    },
    A4: {
      currPage: 1,
    },
    A5: {
      currPage: 1,
    },
    A6: {
      inv: {
        currPage: 1,
      },
      pend: {
        currPage: 1,
      },
    },
  },
  infinite: false,
  teste: '...',
  mocks: {
    A8: {
      requests: [
        {
          id: 'xxx1',
          name: 'solicitação 1',
          image: '',
          status: 'CADASTRO PENDENTE',
        },
        {
          id: 'xxx2',
          name: 'solicitação 2',
          image: '',
          status: 'CADASTRO EFETUADO',
        },
      ],
    },
    A3: {
      selectedData: {
        inventariesList: [
          {
            id: '4',
            codigo: '3',
            name: 'INVENTÁRIO ANUAL DA AEM',
            status: 'EM_ANDAMENTO',
          },
          {
            id: '3',
            codigo: '2',
            name: 'INVENTÁRIO ANUAL LEITOR',
            status: 'EM_ANDAMENTO',
          },
          {
            id: '2',
            codigo: '1',
            name: 'INVENTÁRIO ANUAL DA SAD - 01',
            status: 'EM_ANDAMENTO',
          },
        ],
      },
    },
    A4: {
      selectedData: {
        'Variável Sem Nome': {
          id: 'id',
          navBarTitle: 'Período Inventário',
          status: 'FALTA',
          period: 'period',
          observation: 'observacoes',
          fileName: 'PDF Sem Nome',
          fileUrl: 'Sem Arquivo',
          agencies: {
            allData: [
              {
                id: '1260',
                name: 'LEITORxxxx',
                status: 'INVENTARIO_EM_ANDAMENTO',
              },
              {
                id: '30',
                name: 'SAD',
                status: 'INVENTARIO_EM_ANDAMENTO',
              },
            ],
            'Variável Sem Nome': ['Sem Valor'],
          },
        },
      },
    },
    A5: {
      selectedData: {
        'Variável Sem Nome': {
          id: 'id',
          agency: 'name',
          status: 'status',
          navbarTitle: 'Período Inventário',
          detailsTitle: 'FALTA',
          details: 'FALTA',
          sectors: {
            allData: [
              {
                id: '1431',
                name: 'NUAP',
                status: 'INVENTARIO_EM_ANDAMENTO',
                count: '14',
              },
              {
                id: '1430',
                name: 'NUGESP',
                status: 'INVENTARIO_EM_ANDAMENTO',
                count: '0',
              },
              {
                id: '1428',
                name: 'NUMAN',
                status: 'INVENTARIO_EM_ANDAMENTO',
                count: '14',
              },
              ['Sem Valor'],
            ],
          },
        },
      },
    },
    A6: {
      selectedData: {
        'Variável Sem Nome': {
          id: 'id',
          navbarTitle: 'Período Inventário',
          agency: 'SAD',
          sector: 'NUAP',
          count: '10',
          tabBarCount1: '20',
          tabBarCount2: '30',
          inventories: [
            {
              id: '4',
              code: '000000000000003',
              desc: 'VEICULO - TIPO: ÔNIBUS; QUILOM...',
              condIcon: 'NAO_ENCONTRADO',
              icon: 'ver situacao',
              image: 'null',
              conservation: 'Bom',
              situation: 'NAO_ENCONTRADO',
            },
            {
              id: '7',
              code: '000000000000006',
              desc: 'VEICULO - TIPO: ÔNIBUS; QUILOM...',
              condIcon: 'INVENTARIADO',
              icon: 'ver situacao',
              image: 'null',
              conservation: 'Bom',
              situation: 'INVENTARIADO',
            },
          ],
          pendings: [
            {
              id: '6',
              numero: '000000000000005',
              desc: 'VEICULO - TIPO: ÔNIBUS; QUI...',
            },
            {
              id: '8',
              numero: '000000000000007',
              desc: 'VEICULO - TIPO: ÔNIBUS; QUI...',
            },
          ],
        },
      },
    },
    materialList: [
      {
        id: '1',
        codigo: '000001',
        descricao: 'Lorem ipsum 1',
      },
      {
        id: '2',
        codigo: '000002',
        descricao: 'Lorem ipsum 2',
      },
    ],
    selectedMaterial: [
      {
        id: '1',
        codigo: '000001',
        descricao: 'Tipo',
        valores: ['Cadeira', 'Mesa', 'Armário', 'Computador'],
      },
      {
        id: '2',
        codigo: '000002',
        descricao: 'Cor',
        valores: ['Marrom', 'Azul', 'Preta', 'Branca', 'Vermelha'],
      },
    ],
  },
  all: {
    api: {
      host: 'https://www.siga.ms.gov.br',
      url: 'patrimonio-mobiliario/api/patrimonios/incorporacao/itens/estadosConservacao',
      proxy: 'https://us-central1-flaxboll.cloudfunctions.net/proxyCall',
      auth: {
        cookie: '',
      },
    },
  },
  autocomp: {
    allData: [
      {
        name: 'Carlos Alberto',
      },
      {
        name: 'Leandro Rodrigues',
      },
    ],
    filteredData: ['Sem Valor'],
  },
  mergedObj: {
    id: '',
    code: '',
    navbarTitle: '',
    navbarTitle2: '',
    agency: '',
    sector: '',
    sectorInv: '',
    codeBar: '',
    desc: '',
    obs: '',
    conservation: {
      id: '',
      nome: '',
    },
    icon: '',
    image: '',
    images: ['Sem Valor'],
    status: '',
    count: '',
    details: '',
    pickerList: '',
  },
  sc: {
    A9: {
      picker1: {
        boxState: 'select',
        txtSelected: 'Selecione...',
        txtList: ['Item 1', 'Item 2', 'Item 3'],
        dynamicState: '0',
      },
      picker1A: {
        boxState: 'select',
        txtSelected: 'Selecione...',
        txtList: ['Item 1', 'Item 2', 'Item 3'],
        dynamicState: '0',
      },
      picker1A1: {
        boxState: 'select',
        txtSelected: 'Selecione...',
        txtList: ['Item 1', 'Item 2', 'Item 3'],
        dynamicState: '0',
      },
      picker1A2: {
        boxState: 'select',
        txtSelected: 'Selecione...',
        txtList: ['Item 1', 'Item 2', 'Item 3'],
        dynamicState: '0',
      },
      picker1B1: {
        boxState: 'select',
        txtSelected: 'Selecione...',
        txtList: ['Item 1', 'Item 2', 'Item 3'],
        dynamicState: '0',
      },
      picker1C1: {
        boxState: 'select',
        txtSelected: 'Selecione...',
        txtList: ['Item 1', 'Item 2', 'Item 3'],
        dynamicState: '0',
      },
      picker1C2: {
        boxState: 'select',
        txtSelected: 'Selecione...',
        txtList: ['Item 1', 'Item 2', 'Item 3'],
        dynamicState: '0',
      },
      picker2: {
        boxState: 'select',
        txtSelected: 'Selecione...',
        txtList: ['Item 1', 'Item 2', 'Item 3'],
      },
      materials: [
        {
          id: '- 12',
          descricao: 'Carregando...',
        },
      ],
      pickerMaterial: {
        boxState: 'select',
        txtSelected: 'Selecione...',
        txtList: ['Item 1', 'Item 2', 'Item 3'],
        dynamicState: '0',
      },
      iptsChanges: {
        estadoConservacaoId: '',
        materialId: '',
        caracteristicas: [],
        observacoes: '',
      },
      cameraComp: 'false',
      resCaract: [],
      arrayUri: ['Sem Valor'],
    },
    A7: {
      'propriedade sem nome': '',
    },
    A1: {
      loadingVersion: 'false',
    },
  },
};
